[package]
name = "cvt"
version = "0.0.1"
authors = ["anthony"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.6"
csv = "1.1"
